### ISSUE TITLE
MDNS Service Publishing Failed on WIFI Interface 

### ISSUE THREAD

**Issue by rameshpasunoori** [mdns-js/node-mdns-js#57]
Hello All

Publishing the service failed on WIFI interface

**Case1:**
Excluding the interface "0.0.0.0" (mdns.excludeInterface('0.0.0.0'))
In server code when exclude interface called we getting the error
**Error: addMembership EADDRNOTAVAIL**
Log File: exclude_interface_service.txt

**Case2:**
In server code without exclude interface getting error 
**Error: send EHOSTUNREACH 224.0.0.251:5353 +2ms**
Log File: service.txt

Blocked with this issue please provide some inputs.

[exclude_interface_service.txt](https://github.com/mdns-js/node-mdns-js/files/302906/exclude_interface_service.txt)
[service.txt](https://github.com/mdns-js/node-mdns-js/files/302905/service.txt)

**Comment by whitef0x0** [comment]
What do you exactly mean by WiFi interface? Like eth0 or something?

**Comment by kmpm** [comment]
sounds as if it doesn't find any interfaces in lib/networking.js.
could you on your machine run the following in node and provide me with the output.
```javascript
var os=require('os');
console.log(os.networkInterfaces());
```

**Comment by tsn731** [comment]
the send error EHOSTUNREACH is caused by a missing entry in the routing table for the 224.0.0.251 address. I had to add one manually for my link local interface in order get this to work.
