### ISSUE TITLE
 can node-mdns-js publish a service ?  tell other PC it's SSH,FTP,HTTP service? any plan 2 develop?

### ISSUE THREAD

**Issue by liulover5** [mdns-js/node-mdns-js#69]

**Comment by kmpm** [comment]
Yes it can. Have a look at examples/service.js
I know people are using it but there are certainly some bugs and all features is not fully implemented.
There is currently not active effort to do more work on the service parts but feel free to do it yourself. Pull requests are more then welcome.

Also, as it says in the README.md, there will be trouble if you run it on a computer that has for example avahi or mDNSResponder/Bonjour.

**Comment by liulover5** [comment]
ths !!!
