### ISSUE TITLE
Bug with TXT field

### ISSUE THREAD

**Issue by SerebryanskiySergei** [mdns-js/node-mdns-js#70]
When I'm trying to create advert with field in TXT part, that have a dot inside, it separates in several fields.
Creating: 
  ...
      txt: {
        api_proto: protocol,
        api_ver: 'v1.0',
        // deprecated
        pri: paramsPriority
      }
...

Result: 
txt: [
    "api_proto=http",
     "api_ver=v1",
     "0",
     "pri=100"
]

I've tried to put escape character \ before dot (  api_ver: 'v1\.0', ) but result is the same.

**Comment by kmpm** [comment]
Do you have any code examples?
